[package]
name = "shef-top"
version = "0.1.0"
authors = ["Ana Gelez <ana@gelez.xyz>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"
juniper = { version = "0.14", features = [ "serde_json" ] }
juniper_rocket = "0.5"
rocket = "0.4"
sled = "0.31"
